# Generated by Django 6.0.4 on 2026-04-13 13:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('external_url', models.URLField(help_text='Link to the actual article')),
                ('platform_name', models.CharField(max_length=50)),
                ('cover_image', models.ImageField(upload_to='articles/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('demo_url', models.URLField(blank=True, help_text='Live link to the working application', null=True)),
                ('github_url', models.URLField(blank=True, help_text='Link to the source code', null=True)),
                ('writeup_url', models.URLField(blank=True, help_text='Link to a blog post explaining the technical details', null=True)),
                ('cover_image', models.ImageField(upload_to='projects/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
