# Generated by Django 6.0.4 on 2026-06-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_cover_image_alter_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
