# Generated by Django 6.0.4 on 2026-09-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_article_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
